language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

cache: bundler

before_install: gem install bundler

script: bundle exec rspec
